_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 55
            "2":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 55
            "3":
                - 15
                - 16
                - 23
                - 55
            "4": 3.12.7
            "5": 0.18.5
            "6": 4.46.0
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
config:
    value: config/tent.yaml
dataset:
    value:
        batch_size: 64
        corruptions:
            - gaussian_noise
            - shot_noise
            - impulse_noise
            - defocus_blur
            - glass_blur
            - motion_blur
            - zoom_blur
            - snow
            - frost
            - fog
            - brightness
            - contrast
            - elastic_transform
            - pixelate
            - jpeg_compression
        levels:
            - 5
        name: imagenet-c
        num_workers: 4
        shuffle: true
mode:
    value: train
model:
    value:
        name: resnet-50
        pretrained: true
optimizer:
    value:
        lr: 0.00025
        momentum: 0.9
        name: SGD
        weight_decay: 0.01
trainer:
    value:
        name: TentTrainer
