_wandb:
    value:
        cli_version: 0.18.6
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 55
                - 63
            "2":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 55
                - 63
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.7
            "5": 0.18.6
            "6": 4.46.2
            "8":
                - 5
            "12": 0.18.6
            "13": linux-x86_64
config:
    value: config/tent_resnet50.yaml
dataset:
    value:
        batch_size: 128
        name: ImageNetAll
        num_workers: 12
        path: ./data/
        shuffle: true
device:
    value: cuda:4,5,6
mode:
    value: train
model:
    value:
        name: resnet50
optimizer:
    value:
        lr: 0.00025
        momentum: 0.9
        name: SGD
        weight_decay: 0.01
trainer:
    value:
        name: TentTrainer
