_wandb:
    value:
        cli_version: 0.18.6
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 55
                - 63
            "2":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 55
                - 63
            "3":
                - 15
                - 16
                - 17
                - 23
                - 55
            "4": 3.12.7
            "5": 0.18.6
            "6": 4.46.2
            "8":
                - 5
            "12": 0.18.6
            "13": linux-x86_64
config:
    value: config/tent.yaml
dataset:
    value:
        batch_size: 64
        corruptions:
            - gaussian_noise
            - shot_noise
            - impulse_noise
            - defocus_blur
            - glass_blur
            - motion_blur
            - zoom_blur
            - snow
            - frost
            - fog
            - brightness
            - contrast
            - elastic_transform
            - pixelate
            - jpeg_compression
        levels:
            - 5
        name: ImageNetC
        num_workers: 4
        path: ./data/
        shuffle: true
dataset.batch_size:
    value: 64
dataset.corruptions:
    value:
        - gaussian_noise
        - shot_noise
        - impulse_noise
        - defocus_blur
        - glass_blur
        - motion_blur
        - zoom_blur
        - snow
        - frost
        - fog
        - brightness
        - contrast
        - elastic_transform
        - pixelate
        - jpeg_compression
dataset.levels:
    value:
        - 5
dataset.name:
    value: ImageNetC
dataset.num_workers:
    value: 4
dataset.path:
    value: ./data/
dataset.shuffle:
    value: true
mode:
    value: train
model:
    value:
        name: resnet50
model.name:
    value: resnet50
optimizer:
    value:
        lr: 0.00025
        momentum: 0.9
        name: SGD
        weight_decay: 0.01
optimizer.lr:
    value: 0.00025
optimizer.momentum:
    value: 0.9
optimizer.name:
    value: SGD
optimizer.weight_decay:
    value: 0.01
trainer:
    value:
        device: 0
        name: TentTrainer
trainer.device:
    value: 0
trainer.name:
    value: TentTrainer
