model:
  name: resnet-50 # [resnet-50]
  pretrained: True

dataset:
  name: ImageNetC
  path: ./data/
  corruptions:
    - 'gaussian_noise'
    - 'shot_noise'
    - 'impulse_noise'
    - 'defocus_blur'
    - 'glass_blur'
    - 'motion_blur'
    - 'zoom_blur'
    - 'snow'
    - 'frost'
    - 'fog'
    - 'brightness'
    - 'contrast'
    - 'elastic_transform'
    - 'pixelate'
    - 'jpeg_compression'
  levels:
    - 5

  batch_size: 64
  num_workers: 4
  shuffle: True

optimizer:
  name: SGD
  lr: 0.00025
  weight_decay: 0.01
  momentum: 0.9

trainer:
  name: TentTrainer

  device: 0