_wandb:
    value:
        cli_version: 0.18.6
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 55
                - 63
            "2":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 55
                - 63
            "3":
                - 13
                - 23
                - 55
            "4": 3.12.7
            "5": 0.18.6
            "6": 4.46.2
            "8":
                - 5
            "12": 0.18.6
            "13": linux-x86_64
        visualize:
            domain_accuracy:
                panel_config:
                    fieldSettings:
                        label: domain_id
                        value: top1_acc
                    panelDefId: wandb/bar/v0
                    stringSettings:
                        title: Accuracy per Domain
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: domain_accuracy_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
